### ISSUE TITLE
copy data fails

### ISSUE THREAD

**Issue by sinadogru** [NCCA/BlankNGL#1]
Hello,

I have compiled the library and tried to if i compiled it successfully so I just started with that blank example.

I use shadow build, and when i ran qmake and then make, make fails. Here is the make output,

```
g++ -c -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/home/cavit/projects/NGLProjects/BlankNGL -I. -I/home/cavit/projects/NGLProjects/BlankNGL/include -I/home/cavit/NGL/include -I/home/cavit/NGL/include -I/home/cavit/Qt/5.5/gcc_64/include -I/home/cavit/Qt/5.5/gcc_64/include/QtOpenGL -I/home/cavit/Qt/5.5/gcc_64/include/QtWidgets -I/home/cavit/Qt/5.5/gcc_64/include/QtGui -I/home/cavit/Qt/5.5/gcc_64/include/QtCore -Imoc -I/home/cavit/Qt/5.5/gcc_64/mkspecs/linux-g++ -o obj/main.o /home/cavit/projects/NGLProjects/BlankNGL/src/main.cpp
In file included from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
                 from /home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
                 from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
                 from /home/cavit/projects/NGLProjects/BlankNGL/include/NGLScene.h:8,
                 from /home/cavit/projects/NGLProjects/BlankNGL/src/main.cpp:6:
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
g++ -c -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/home/cavit/projects/NGLProjects/BlankNGL -I. -I/home/cavit/projects/NGLProjects/BlankNGL/include -I/home/cavit/NGL/include -I/home/cavit/NGL/include -I/home/cavit/Qt/5.5/gcc_64/include -I/home/cavit/Qt/5.5/gcc_64/include/QtOpenGL -I/home/cavit/Qt/5.5/gcc_64/include/QtWidgets -I/home/cavit/Qt/5.5/gcc_64/include/QtGui -I/home/cavit/Qt/5.5/gcc_64/include/QtCore -Imoc -I/home/cavit/Qt/5.5/gcc_64/mkspecs/linux-g++ -o obj/NGLScene.o /home/cavit/projects/NGLProjects/BlankNGL/src/NGLScene.cpp
In file included from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
                 from /home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
                 from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
                 from /home/cavit/projects/NGLProjects/BlankNGL/include/NGLScene.h:8,
                 from /home/cavit/projects/NGLProjects/BlankNGL/src/NGLScene.cpp:4:
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
g++ -Wl,-rpath,/home/cavit/Qt/5.5/gcc_64 -Wl,-rpath,/home/cavit/NGL/lib -Wl,-rpath,/home/cavit/Qt/5.5/gcc_64/lib -o ./BlankNGL obj/main.o obj/NGLScene.o   -L/usr/local/lib -L/home/cavit/NGL/lib -l NGL -ltiff -L/home/cavit/Qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
echo creating destination dirs ; mkdir -p /home/cavit/builds/BlankNGL-Desktop_Qt_5_5_1_GCC_64bit-Debug/shaders ; echo copying files ; cp -f -R /home/cavit/projects/NGLProjects/BlankNGL/shaders/* /home/cavit/builds/BlankNGL-Desktop_Qt_5_5_1_GCC_64bit-Debug/shaders/ ;
creating destination dirs
copying files
cp: cannot stat '/home/cavit/projects/NGLProjects/BlankNGL/shaders/*': No such file or directory
make: *** [copydata] Error 1
12:04:33: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project BlankNGL (kit: Desktop Qt 5.5.1 GCC 64bit)
When executing step "Make"
```

I guess it fails on the BlankNGL.pro file on the line 40: 
copydata.commands += $(COPY_DIR) $$PWD/shaders/\* $$OUT_PWD/shaders/ ;

I have also checked if there is any shaders folder on the project folder, but it does not exists.

Can you please address if am I doing something wrong?

Also as a bonus, can you please tell me how can I suppress those Qt warnings about GLEW? 

Thank you,
Sina

**Comment by jmacey** [comment]
yes you need to turn off shadow build and it will fix it all, (or create a shaders directory and this will fix it as well),
On 10 Mar 2016, at 10:08, sinadogru <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I have compiled the library and tried to if i compiled it successfully so I just started with that blank example.

I use shadow build, and when i ran qmake and then make, make fails. Here is the make output,

g++ -c -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/home/cavit/projects/NGLProjects/BlankNGL -I. -I/home/cavit/projects/NGLProjects/BlankNGL/include -I/home/cavit/NGL/include -I/home/cavit/NGL/include -I/home/cavit/Qt/5.5/gcc_64/include -I/home/cavit/Qt/5.5/gcc_64/include/QtOpenGL -I/home/cavit/Qt/5.5/gcc_64/include/QtWidgets -I/home/cavit/Qt/5.5/gcc_64/include/QtGui -I/home/cavit/Qt/5.5/gcc_64/include/QtCore -Imoc -I/home/cavit/Qt/5.5/gcc_64/mkspecs/linux-g++ -o obj/main.o /home/cavit/projects/NGLProjects/BlankNGL/src/main.cpp
In file included from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
from /home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
from /home/cavit/projects/NGLProjects/BlankNGL/include/NGLScene.h:8,
from /home/cavit/projects/NGLProjects/BlankNGL/src/main.cpp:6:
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
#warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
^
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include or after glew.h [-Wcpp]
#warning To use GLEW with Qt, do not include or after glew.h
^
g++ -c -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=c++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/home/cavit/projects/NGLProjects/BlankNGL -I. -I/home/cavit/projects/NGLProjects/BlankNGL/include -I/home/cavit/NGL/include -I/home/cavit/NGL/include -I/home/cavit/Qt/5.5/gcc_64/include -I/home/cavit/Qt/5.5/gcc_64/include/QtOpenGL -I/home/cavit/Qt/5.5/gcc_64/include/QtWidgets -I/home/cavit/Qt/5.5/gcc_64/include/QtGui -I/home/cavit/Qt/5.5/gcc_64/include/QtCore -Imoc -I/home/cavit/Qt/5.5/gcc_64/mkspecs/linux-g++ -o obj/NGLScene.o /home/cavit/projects/NGLProjects/BlankNGL/src/NGLScene.cpp
In file included from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
from /home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
from /home/cavit/Qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
from /home/cavit/projects/NGLProjects/BlankNGL/include/NGLScene.h:8,
from /home/cavit/projects/NGLProjects/BlankNGL/src/NGLScene.cpp:4:
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
#warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
^
/home/cavit/Qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include or after glew.h [-Wcpp]
#warning To use GLEW with Qt, do not include or after glew.h
^
g++ -Wl,-rpath,/home/cavit/Qt/5.5/gcc_64 -Wl,-rpath,/home/cavit/NGL/lib -Wl,-rpath,/home/cavit/Qt/5.5/gcc_64/lib -o ./BlankNGL obj/main.o obj/NGLScene.o -L/usr/local/lib -L/home/cavit/NGL/lib -l NGL -ltiff -L/home/cavit/Qt/5.5/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread
echo creating destination dirs ; mkdir -p /home/cavit/builds/BlankNGL-Desktop_Qt_5_5_1_GCC_64bit-Debug/shaders ; echo copying files ; cp -f -R /home/cavit/projects/NGLProjects/BlankNGL/shaders/\* /home/cavit/builds/BlankNGL-Desktop_Qt_5_5_1_GCC_64bit-Debug/shaders/ ;
creating destination dirs
copying files
cp: cannot stat '/home/cavit/projects/NGLProjects/BlankNGL/shaders/': No such file or directory
make: *\* [copydata] Error 1
12:04:33: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project BlankNGL (kit: Desktop Qt 5.5.1 GCC 64bit)
When executing step "Make"

I guess it fails on the BlankNGL.pro file on the line 40:
copydata.commands += $(COPY_DIR) $$PWD/shaders/\* $$OUT_PWD/shaders/ ;

I have also checked if there is any shaders folder on the project folder, but it does not exists.

Can you please address if am I doing something wrong?

Thank you,
Sina

—
Reply to this email directly or view it on GitHubhttps://github.com/NCCA/BlankNGL/issues/1.

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by sinadogru** [comment]
Thank you for your reply, I disabled it and it is working now but I guess because of the version of my open gl I do have some problems, would you please help? those just appeared on "SimpleNGL".

Here is the output, 

```
./SimpleNGL 
Profile is 4 5
Using GLEW 1.11.0
ngl:: configured with GL version 3.3
Compiling Shader nglTextVertex
Compiling Shader nglTextFragment
GL error GL_INVALID_ENUM error line : 87 file : src/ShaderProgram.cpp
Linking nglTextShader
linking Shader nglTextShader

Compiling Shader nglColourVertex
Compiling Shader nglColourFragment
Linking nglColourShader
linking Shader nglColourShader

Compiling Shader nglDiffuseVertex
Compiling Shader nglDiffuseFragment
Linking nglDiffuseShader
linking Shader nglDiffuseShader

Compiling Shader nglToonVertex
Compiling Shader nglToonFragment
Linking nglToonShader
linking Shader nglToonShader

creating empty ShaderProgram Phong
just attached PhongVertex 14
just attached PhongFragment 15
deleting existing source code
deleting existing source code
Compiling Shader PhongVertex
Shader compile failed or had warnings 
0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

Closing down shader manager
removing ShaderProgram Phong
removing ShaderProgram nglToonShader
removing ShaderProgram nglDiffuseShader
removing ShaderProgram nglTextShader
removing ShaderProgram nglColourShader
removing ShaderProgram NULL
removing shader PhongVertex
removing shader nglToonVertex
removing shader nglDiffuseVertex
removing shader nglColourFragment
removing shader nglColourVertex
removing shader PhongFragment
removing shader nglTextFragment
removing shader nglToonFragment
removing shader nglDiffuseFragment
removing shader nglTextVertex
```

And my open gl informations,

```
glxinfo | grep versionserver glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
```

Thank you,
Sina

**Comment by jmacey** [comment]
change the shader lines that say

#version 410 core to 330 core
On 10 Mar 2016, at 13:52, sinadogru <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you for your reply, I disabled it and it is working now but I guess because of the version of my open gl I do have some problems, would you please help? those just appeared on "SimpleNGL".

Here is the output,

./SimpleNGL
Profile is 4 5
Using GLEW 1.11.0
ngl:: configured with GL version 3.3
Compiling Shader nglTextVertex
Compiling Shader nglTextFragment
GL error GL_INVALID_ENUM error line : 87 file : src/ShaderProgram.cpp
Linking nglTextShader
linking Shader nglTextShader

Compiling Shader nglColourVertex
Compiling Shader nglColourFragment
Linking nglColourShader
linking Shader nglColourShader

Compiling Shader nglDiffuseVertex
Compiling Shader nglDiffuseFragment
Linking nglDiffuseShader
linking Shader nglDiffuseShader

Compiling Shader nglToonVertex
Compiling Shader nglToonFragment
Linking nglToonShader
linking Shader nglToonShader

creating empty ShaderProgram Phong
just attached PhongVertex 14
just attached PhongFragment 15
deleting existing source code
deleting existing source code
Compiling Shader PhongVertex
Shader compile failed or had warnings
0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

Closing down shader manager
removing ShaderProgram Phong
removing ShaderProgram nglToonShader
removing ShaderProgram nglDiffuseShader
removing ShaderProgram nglTextShader
removing ShaderProgram nglColourShader
removing ShaderProgram NULL
removing shader PhongVertex
removing shader nglToonVertex
removing shader nglDiffuseVertex
removing shader nglColourFragment
removing shader nglColourVertex
removing shader PhongFragment
removing shader nglTextFragment
removing shader nglToonFragment
removing shader nglDiffuseFragment
removing shader nglTextVertex

And my open gl informations,

glxinfo | grep versionserver glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30

Thank you,
Sina

—
Reply to this email directly or view it on GitHubhttps://github.com/NCCA/BlankNGL/issues/1#issuecomment-194849243.

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by sinadogru** [comment]
phew, it is the time to start study shader language :). Thanks for your helps :+1:
